# Put this file in your home directory
startrek_token: your_token_here

# Stuff below is optional:

month_start: 16  # Meaning closed tickets are grouped by May 16-June 15, June 16-July 16 and so on.

component_suffixes:  # suffixes for cohort definition according to course
  backend-developer: ''
  python-developer-plus: '+'

download:
    directory: path/to/downloaded/homeworks
    browser:
        type: firefox  # Only Firefox is supported ATM
        profile_path: path/to/firefox/profile  # Note: no trailing slash on *nix environments
        # E.g. /Users/<username>/Library/Application Support/Firefox/Profiles/<something>.default-release
        # For details on your profile location see https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data
process:
    # Which steps are applied?
    # 1. The steps in process.default
    # 2. If the course name matches, the steps in process.courses.<course_name>.default
    # 3. If the problem number matches as well, the steps in process.courses.<course_name>.problems.<problem_number>
    runner: ["bash", "-c"]
    default:
        steps:
            # The following variables are supported:
            #
            # hw -- the absolute path of the homework directory
            # it_last -- the absolute path of the last iteration directory
            # it_last_ -- the path of the last iteration directory relative to the homework directory
            # it_last_zip and it_last_zip_ are similar, but point to zip files
            # it_prev and friends refer to the corresponding counterparts for the previous iteration
            # if it_prev if present the step is skipped for the first iteration
            diff: "cd {hw} && diff -r -N {it_prev_} {it_last_}"
            # Check out https://github.com/jeffkaufman/icdiff for a better alternative.
    courses:
        backend-developer:
            default:
                steps:
                    pycodestyle: "/usr/local/bin/pycodestyle {it_last} | grep -v -e 'master/tests/' -e migrations -e settings"
            problems:
                2:
                    steps:
                        find_set_null: "cd {it_last} && grep -r SET_NULL ."
